// enum for environment variables in configuration file .env
export enum XEnvVar {
    REACT_APP_BACKEND_URL = 'REACT_APP_BACKEND_URL',
    REACT_APP_AUTH = 'REACT_APP_AUTH',

    REACT_APP_AUTH_OFF_USERNAME = 'REACT_APP_AUTH_OFF_USERNAME',

    REACT_APP_AUTH0_DOMAIN = 'REACT_APP_AUTH0_DOMAIN',
    REACT_APP_AUTH0_CLIENT_ID = 'REACT_APP_AUTH0_CLIENT_ID',
    REACT_APP_AUTH0_AUDIENCE = 'REACT_APP_AUTH0_AUDIENCE',
    //REACT_APP_AUTH0_SCOPE = 'REACT_APP_AUTH0_SCOPE'

    REACT_APP_MS_ENTRA_ID_TENANT_ID = 'REACT_APP_MS_ENTRA_ID_TENANT_ID',
    REACT_APP_MS_ENTRA_ID_CLIENT_ID = 'REACT_APP_MS_ENTRA_ID_CLIENT_ID',
    REACT_APP_MS_ENTRA_ID_BACKEND_SCOPE = 'REACT_APP_MS_ENTRA_ID_BACKEND_SCOPE'
}

// enum for values of the environment variable REACT_APP_AUTH
export enum XReactAppAuth {
    OFF = 'OFF',
    LOCAL = 'LOCAL',
    AUTH0 = 'AUTH0',
    MS_ENTRA_ID = 'MS_ENTRA_ID'
}
